# Generated by Django 4.0.2 on 2022-03-01 05:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_image_alter_course_course_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_course_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.category', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Yayımlanma Tarihi'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(blank=True, verbose_name='Kurs Açıklaması'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, default='no_image.png', upload_to='images/%Y/%m/%d/', verbose_name='Resim Dosyası'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=200, verbose_name='Kurs Adı'),
        ),
    ]
