# Generated by Django 4.0.2 on 2022-03-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
            ],
        ),
    ]
