# Generated by Django 4.0.2 on 2022-03-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_tags',
            field=models.ManyToManyField(blank=True, null=True, to='courses.Tag'),
        ),
    ]
