# Generated by Django 4.0.2 on 2022-03-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_course_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_tags',
            field=models.ManyToManyField(blank=True, to='courses.Tag'),
        ),
    ]
