# Generated by Django 4.0.2 on 2022-03-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('teacher_title', models.CharField(max_length=200)),
                ('teacher_description', models.TextField(blank=True)),
                ('teacher_image', models.ImageField(upload_to='teachers/')),
                ('teacher_facebook', models.URLField(blank=True, max_length=100)),
                ('teacher_twitter', models.URLField(blank=True, max_length=100)),
                ('teacher_linkedin', models.URLField(blank=True, max_length=100)),
                ('teacher_github', models.URLField(blank=True, max_length=100)),
            ],
        ),
    ]
